@TmsApi_HostAddress = http://localhost:5249

GET {{TmsApi_HostAddress}}/api/assessments/results
Accept: application/json

###

GET {{TmsApi_HostAddress}}/api/assessments/results
X-Training-User: Abdulfeta
Accept: application/json

###

GET {{TmsApi_HostAddress}}/worker-smoke
Accept: application/json

###

GET {{TmsApi_HostAddress}}/test-notfound/abc123
Accept: application/json

###