@TmsApi_HostAddress = http://localhost:5249
# @TmsApi_HostAddress = http://localhost:5000


GET {{TmsApi_HostAddress}}/api/assessments/results
Accept: application/json

###

GET {{TmsApi_HostAddress}}/api/assessments/results
X-Training-User: Abdulfeta
Accept: application/json

# Module 4 Lab Session 3: Exercise 5: The Enrollment API (Controllers with Real CRUD)

### 1. GET all enrollments (empty list)
GET {{TmsApi_HostAddress}}/api/enrollments
Accept: application/json

###

### 2. POST a new enrollment
POST {{TmsApi_HostAddress}}/api/enrollments
Content-Type: application/json

{
  "studentId": "S-001",
  "courseCode": "CS-101"
}

###

### 3. GET created enrollment
# Replace the ID after POST response
GET {{TmsApi_HostAddress}}/api/enrollments/0acba511
Accept: application/json

###

### 4. DELETE the enrollment
# Replace the ID after POST response
DELETE {{TmsApi_HostAddress}}/api/enrollments/0acba511

###

### 5. GET deleted enrollment
# Replace the ID after DELETE
GET {{TmsApi_HostAddress}}/api/enrollments/0acba511
Accept: application/json

### 6. ProblemDetails test
GET {{TmsApi_HostAddress}}/api/error
Accept: application/json


### 
GET {{TmsApi_HostAddress}}/api/test/deferred
###
GET {{TmsApi_HostAddress}}/api/test/translation-fail

###
GET {{TmsApi_HostAddress}}/api/reports/active-students-count

###
GET {{TmsApi_HostAddress}}/api/reports/course-enrollments

###
GET {{TmsApi_HostAddress}}/api/reports/average-gpa-per-course

###
GET {{TmsApi_HostAddress}}/api/reports/students-without-enrollments-a

###
GET {{TmsApi_HostAddress}}/api/reports/students-without-enrollments-b

###
Get {{TmsApi_HostAddress}}/api/reports/students

###
Get {{TmsApi_HostAddress}}/api/reports/students?page=2

###
Get {{TmsApi_HostAddress}}/api/reports/top-courses

###
GET {{TmsApi_HostAddress}}/api/reports/n-plus-one-demo

###
GET {{TmsApi_HostAddress}}/api/reports/n-plus-one-fixed